### ISSUE TITLE
Gängige Wendungen

### ISSUE THREAD

**Issue by JanCoenen** [KataSchubert/M19_19.3_WPM_T9.1_Schubert#5]
Gängige Wendungen wie "das heißt" oder "zum Beispiel" sollten nach Möglichkeit nicht abgekürzt, sondern ausgeschrieben werden. Dabei handelt es sich aber wohl um eine Frage des persönlichen Geschmacks.

**Comment by KataSchubert** [comment]
Jepp, aber find ich gut und werde ich ändern.
